name: frontend
description: Flicker frontend application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 
  flutter_svg: ^2.0.10
  
  # Библиотека для работы с сетью и бэкендом
  dio: ^5.4.0
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding_1.jpg
    - assets/images/onboarding_2.jpg
    - assets/images/onboarding_3.jpg
    - assets/icons/ru_flag.svg
  # В будущем, когда ты скачаешь картинки или шрифты (Manrope, Inter), 
  # их нужно будет раскомментировать и прописать здесь:
  # assets:
  #   - assets/images/
  #
  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #       - asset: assets/fonts/Manrope-Bold.ttf
  #         weight: 700


  